### ISSUE TITLE
Level 1

### ISSUE THREAD

**Issue by Riclas1** [mischah/js-tooling-demo#1]
Hallo,

wollte Ihrer Videoserie folgen. Wo finde ich denn level 1 bis 7?

Im Voraus vielen Dank

Rico Sonntag

**Comment by mischah** [comment]
Hej Rico,

die einzelnen Steps sind via Git Tags markiert:
![image](https://cloud.githubusercontent.com/assets/441011/24625552/aa7bbcda-18af-11e7-9a5c-223e21773842.png)


VG Michael
